services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 admin_dashboard.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: sh -c "export HOST=0.0.0.0 && npm start"
    environment:
      - HOST=0.0.0.0

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lab@123
      - POSTGRES_DB=farming_db

  redis:
    image: redis:7

volumes:
  postgres_data: