version: "3.9"

services:
  # Backend (Django)
  backend:
    build: ./backend
    container_name: farming_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  # Frontend (React)
  frontend:
    build: ./frontend
    container_name: farming_frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: farming_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Admin_Dashboard
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7
    container_name: farming_redis
    ports:
      - "6379:6379"
